### ISSUE TITLE
Do poprawy

### ISSUE THREAD

**Issue by kacgrzes** [Taporpone/Node#1]
- [x] nie ma potrzeby robić enterów pomiędzy kolejnymi przypadkami. Wcięcia świetnie sobie z tym radzą
- [x] umówmy się, że do kodu wystawiasz issues'y zmiast komentarzy
- [x] `language === undefined` trochę przekombinowane. Można było użyć [ternary operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator)
- [x] to samo tyczy się komendy `/ver`

pomysłowe z tym `process.exit` 👍

**Comment by Taporpone** [comment]
Nie rozumiem przekombinowania w 3 punkcie?

**Comment by kacgrzes** [comment]
fajnie, że sprawdzasz warunek, ale możesz zrobić
``` js
if (!language)
```
zamiast
``` js
if(language === undefined)
```
opcjonalnie można by też użyć ternary operator i napisać cały. 5-cio linijkowy warunek, w następujący sposób:
``` js
var hasLanguage = !!language;
hasLanguage ? process.stdout.write('Node version: ' + version + '\n') : process.stderr.write("Thats strange since you are running this script using node, BUT I can't read node's version O.o\n");
```
Twoja wersja jest jak najbardziej w porządku :) czepiam się tylko `language === undefined`.

**Comment by Taporpone** [comment]
Ah, przeoczylem fakt, ze bool undefined to false, kumam juz.

**Comment by kacgrzes** [comment]
no problemo

**Comment by Taporpone** [comment]
Czy ten fragment, prosto z tutoriala, nie jest analogiczny?
`var input = process.stdin.read();
  if (input !== null){`

**Comment by kacgrzes** [comment]
niestety nie. Pusty tekst (wciśnięcie spacji, a następnie skasowanie jej) będzie skutkowało wyjściem z warunku mimo, że jest to prawidłowa wartość. `null` to wartość, która oznacza - brak wartości
``` js
var a = '', testA = !a;
console.log(testA);
var b = 'tekst', testB = !b;
console.log(testB);
```
Nie wiem czy dostatecznie jasno to napisałem. wejdź na jsbin i poeksperymentuj sobie
